version: "3"

services:
  database:
    image: "mysql:8.0.3"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
 